### PR TITLE
translated parts of basic aep to OpenMDAO1.x including test

### PR DESCRIPTION
**Pull request by BecMax**

### CODE REVIEW

**Comment by fzahle** [comment]
thanks for the contribution. The test works, but if I run a test on the partial derivatives:

    p.check_partial_derivatives()

I get the error:

    ValueError: derivative in component 'aep' of 'gross_aep' wrt 'power_curve' is the wrong size. It should be (1, 26), but got (26, 1)

**Comment by fzahle** [comment]
the shape issue is resolved this way:

        J['gross_aep', 'CDF_V'] = np.array([d_gross_d_cdf])
        J['gross_aep', 'power_curve'] = np.array([d_gross_d_p])
        J['net_aep', 'CDF_V'] = np.array([d_net_d_cdf])
        J['net_aep', 'power_curve'] = np.array([d_net_d_p])

and the next issue that pops up is that `turbine_number` is defined as an integer parameter, which is not differentiable. @dykesk, don't you agree that `turbine_number` should just be defined as an argument to the `__init__` method?

@BecMax when these issues are fixed, its good to go.

**Comment by BecMax** [comment]
Thanks for pointing out the derivative error and already having a solution for it. In my opinion `turbine_number` could also go into the `__init__` method.

**Comment by fzahle** [comment]
@rethore, I'm guessing you will need an all together different AEP comp for your wind farm stuff or could we expand this one to also accommodate your needs? It would be nice not to have too many AEP comps to choose from.

**Comment by fzahle** [comment]
hi @BecMax. Go ahead and add `turbine_number` to the `__init__` and I'll merge it.

**Comment by fzahle** [comment]
please also change the Weibull `A` and `k` param names to `weibull_A` and `weibull_k`. this way when promoted they are self explanatory.

**Comment by fzahle** [comment]
should we get this wrapped up and merged? @dykesk could you also take a look at this? In addition to this AEP comp it would be good to have a component for computing AEP as in `plant_energyse.nrel_csm_aep.aep_csm_component` where instead `hub_height`, `shear_exponent`, `wind_speed_50m` and `weibull_k` are the inputs so an optimisation with hub height as parameter would get a site specific AEP. Should we adapt the code in ´plant-energyse` to OpenMDAO 1.x and put it in FUSED-Wind?

**Pull request merged**
