### PR TITLE
Structure param2

### PR DESCRIPTION
**Pull request by fzahle**
@mrosemeier et al - I've put together a structural parameterisation based on the lofted geometry with more meaningful quantities, see https://github.com/FUSED-Wind/fusedwind-dev/blob/structure_param2/fusedwind/turbine/structure.py#L517 for a list of params. the class is pure python and can be called as a preprocessing step or used as part of an OpenMDAO workflow for optimisation. 

caps and webs are placed relative to a vertical reference plane going from root to tip, making it simple to generate simple structures with straight caps and webs perpendicular to this reference plane. a structural angle can be specified that rotates the entire blade before placing the caps/webs relative to the vertical plane to allow for offset between upper/lower caps

param2

param2a

A new st file with extension `geo3d` can now be specified with the necessary inputs.

would be great if you could test it out and comment/propose changes before I merge it. I'll add some docs asap.

### CODE REVIEW

**Comment by mrosemeier** [comment]
@fzahle This is a nice feature. A minor suggestion might be to use a more concrete naming for 'upper' and 'lower', instead I would prefer 'ss' and 'ps'.

OMDAO 1.7.1, PGL master 5c741f9, ran all 24 tests, (failures=1, errors=2):

```
======================================================================
ERROR: test_curve_length (fusedwind.turbine.test.test_splinedplanform.TestSplinedPlanform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mrosemeier/iwes-gitlab/bdt/fusedwind-dev/fusedwind/turbine/test/test_splinedplanform.py", line 74, in test_curve_length
    self.assertAlmostEqual(p['blade_curve_length'], 1.0032258904912261, places=6)
  File "/home/mrosemeier/iwes-gitlab/bdt/OpenMDAO/openmdao/core/problem.py", line 140, in __getitem__
    raise KeyError("Variable '%s' not found." % name)
KeyError: "Variable 'blade_curve_length' not found."

======================================================================
ERROR: test_pchip (fusedwind.turbine.test.test_splinedplanform.TestSplinedPlanform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mrosemeier/iwes-gitlab/bdt/fusedwind-dev/fusedwind/turbine/test/test_splinedplanform.py", line 60, in test_pchip
    self.assertEqual(np.testing.assert_array_almost_equal(p['athick'], athick_pchip, decimal=6), None)
  File "/home/mrosemeier/iwes-gitlab/bdt/OpenMDAO/openmdao/core/problem.py", line 140, in __getitem__
    raise KeyError("Variable '%s' not found." % name)
KeyError: "Variable 'athick' not found."

======================================================================
FAIL: test_props (fusedwind.turbine.test.test_splinedstructure.TestSplinedBladeStructure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mrosemeier/iwes-gitlab/bdt/fusedwind-dev/fusedwind/turbine/test/test_splinedstructure.py", line 118, in test_props
    self.assertEqual(np.testing.assert_array_almost_equal(p['r04_thickness'], r04_thickness, decimal=4), None)
  File "/home/mrosemeier/miniconda/envs/py27/lib/python2.7/site-packages/numpy/testing/utils.py", line 912, in assert_array_almost_equal
    precision=decimal)
  File "/home/mrosemeier/miniconda/envs/py27/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals

(mismatch 37.5%)
 x: array([ 0.016 ,  0.0609,  0.0781,  0.083 ,  0.0782,  0.0655,  0.0391,
        0.003 ])
 y: array([ 0.032 ,  0.0627,  0.0781,  0.083 ,  0.0782,  0.0655,  0.0391,
        0.013 ])
```

**Comment by fzahle** [comment]
Thanks Malo. I used upper and lower because I thought structural engineers didn't have a notion of suction and pressure side ;-) The naming scheme is also slightly inconsistent with `BladeStructureProperties` where I use `_u`  and `_p`. So I can change all of them to `ps` and `ss`.

The failures you're getting is probably because the `pre_setup` method is not yet in a release but only available on the master branch of OpenMDAO. If you run the test file on its own not using nose you should see a depreciation statement telling you to upgrade.

**Comment by mrosemeier** [comment]
Thanks for the fix. I must tell you that even our technicians in the full-scale blade test facilities use the terms 'ss' and 'ps'; these terms are especially advantageous when the blade is situated upside down in the hall :)

All tests are successful in case I uncomment the deprecated `rotate_planform` function of PGL in  https://github.com/FUSED-Wind/fusedwind-dev/blob/structure_param2/fusedwind/turbine/structure.py#L19

**Comment by fzahle** [comment]
ok, I'll rename to ss and ps then!

**Comment by mrosemeier** [comment]
@fzahle One thing we have thought about is the creation of curved webs/ caps in case you have a swept blade such that the webs/caps follow the sweep spline. Is this possible with your implementation?

**Comment by fzahle** [comment]
@mrosemeier - that can be done by setting the `cap_center_ss` and `cap_center_ps` array inputs. The first version I made used the blade main axis as the reference for positioning the caps and webs, but I ended up using a plane from root to tip to make it easier to generate straight caps. The `ComputeDPsParam2` class does compute and rotate the main axis according to the `struct_angle`, so you could use this to set the cap centers so they follow the sweep axis. Try to play around with it, and if it doesn't work well, we can try to add some methods to deal with this use.

**Comment by fzahle** [comment]
I've modified the code slightly so it now allows for regions to go to zero width. this comes with a matching change in the BECASWrapper that checks for this and pops these regions before generating the mesh. in the above figures region02 between the TE reinforcement and the trailing edge web thus collapses onto the TE reinforcement DP02, and the web will be removed with it in the cs2d definition used in the mesher.

**Comment by fzahle** [comment]
@mrosemeier @tlbl @pilotmm - please review and let me know if you have objections before I merge.

**Pull request merged**
